//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summarize { get; set; }
        public string Link { get; set; }
        public string Photo { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> JustPhoto { get; set; }
        public Nullable<bool> IsHeader { get; set; }
        public string LinkYoutube { get; set; }
        public Nullable<int> BannerIndex { get; set; }
        public string Position { get; set; }
    }
}
