//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.ChildCategory = new HashSet<Category>();
            this.PostCategories = new HashSet<PostCategory>();
            this.TutorialVideos = new HashSet<TutorialVideo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summarize { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsMenu { get; set; }
        public string Controller { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string keyword { get; set; }
        public string MetaKey { get; set; }
        public string MetaDescription { get; set; }
        public string Position { get; set; }
        public string SEOTitle { get; set; }
        public string DisplayType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> ChildCategory { get; set; }
        public virtual Category Category2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostCategory> PostCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorialVideo> TutorialVideos { get; set; }
    }
}
