//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SATEntities : DbContext
    {
        public SATEntities()
            : base("name=SATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<ConsultantRegister> ConsultantRegisters { get; set; }
        public virtual DbSet<Council> Councils { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostCategory> PostCategories { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SATAccount> SATAccounts { get; set; }
        public virtual DbSet<SATAnswer> SATAnswers { get; set; }
        public virtual DbSet<SATContentLine> SATContentLines { get; set; }
        public virtual DbSet<SATExamContent> SATExamContents { get; set; }
        public virtual DbSet<SATExamForm> SATExamForms { get; set; }
        public virtual DbSet<SATScore> SATScores { get; set; }
        public virtual DbSet<SATTest> SATTests { get; set; }
        public virtual DbSet<SATTestSection> SATTestSections { get; set; }
        public virtual DbSet<SATType> SATTypes { get; set; }
        public virtual DbSet<SATUserAnswer> SATUserAnswers { get; set; }
        public virtual DbSet<SATWritingUnderlineText> SATWritingUnderlineTexts { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<StudentHighlight> StudentHighlights { get; set; }
        public virtual DbSet<TeacherHighlight> TeacherHighlights { get; set; }
        public virtual DbSet<TeacherSchedule> TeacherSchedules { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<UniversityHighlight> UniversityHighlights { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ViewSession> ViewSessions { get; set; }
        public virtual DbSet<TutorialVideo> TutorialVideos { get; set; }
        public virtual DbSet<SATQuestion> SATQuestions { get; set; }
    }
}
