//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SATAnswer()
        {
            this.SATUserAnswers = new HashSet<SATUserAnswer>();
        }
    
        public int ID { get; set; }
        public string AnswerContent { get; set; }
        public bool IsRightAnswer { get; set; }
        public bool Status { get; set; }
        public int QuestionID { get; set; }
        public int AnswerType { get; set; }
        public string Mark { get; set; }
        public string Explanation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATUserAnswer> SATUserAnswers { get; set; }
        public virtual SATQuestion SATQuestion { get; set; }
    }
}
