//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATContentLine
    {
        public int ID { get; set; }
        public string LineText { get; set; }
        public int LineIndex { get; set; }
        public int ExamContentID { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual SATExamContent SATExamContent { get; set; }
    }
}
