//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATExamContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SATExamContent()
        {
            this.SATContentLines = new HashSet<SATContentLine>();
            this.SATQuestions = new HashSet<SATQuestion>();
        }
    
        public int ID { get; set; }
        public int ExamContentIndex { get; set; }
        public string AttachImage { get; set; }
        public string Contents { get; set; }
        public bool Status { get; set; }
        public int ExamFormID { get; set; }
        public string Title { get; set; }
        public string Intro { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATContentLine> SATContentLines { get; set; }
        public virtual SATExamForm SATExamForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATQuestion> SATQuestions { get; set; }
    }
}
