//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATExamForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SATExamForm()
        {
            this.SATExamContents = new HashSet<SATExamContent>();
            this.SATTestSections = new HashSet<SATTestSection>();
        }
    
        public int ID { get; set; }
        public string Direction { get; set; }
        public string Title { get; set; }
        public int Duration { get; set; }
        public int NumberQuestion { get; set; }
        public int TypeID { get; set; }
        public int Section { get; set; }
        public bool Status { get; set; }
        public int ExamCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATExamContent> SATExamContents { get; set; }
        public virtual SATType SATType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATTestSection> SATTestSections { get; set; }
    }
}
