//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SATQuestion()
        {
            this.SATAnswers = new HashSet<SATAnswer>();
            this.SATWritingUnderlineTexts = new HashSet<SATWritingUnderlineText>();
        }
    
        public int ID { get; set; }
        public string QuestionContent { get; set; }
        public bool Status { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ExamContentID { get; set; }
        public int QuestionNo { get; set; }
        public Nullable<bool> HasInputAnswer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATAnswer> SATAnswers { get; set; }
        public virtual SATExamContent SATExamContent { get; set; }
        public virtual SATType SATType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATWritingUnderlineText> SATWritingUnderlineTexts { get; set; }
    }
}
