//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATUserAnswer
    {
        public int ID { get; set; }
        public Nullable<int> UserAnswer { get; set; }
        public System.Guid rowguid { get; set; }
        public int TestID { get; set; }
        public string AnswerContent { get; set; }
    
        public virtual SATAnswer SATAnswer { get; set; }
        public virtual SATTest SATTest { get; set; }
    }
}
