//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEE.Infrastructure.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialVideo
    {
        public int ID { get; set; }
        public string Link { get; set; }
        public string Title { get; set; }
        public bool Status { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> CatId { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
